image:
  repository: "216612008115216612008115.dkr.ecr.us-east-1.amazonaws.com/lesson7-django-repo"
  tag: latest

region: "us-east-1"

service:
  type: LoadBalancer
  port: 80

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

env:
  DJANGO_SECRET_KEY: "django-insecure-+bd+zv#o@fyb8#u%qcbs(owpwmesa@xv%!yiry+zu(nco7&k3$"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "*"

postgresql:
  enabled: false
  host: "prod-db.cwxgmq8gqhxc.us-east-1.rds.amazonaws.com"
  port: "5432"
  db: "appdb_1753463128"
  user: "admin_1753463128"
  password: "rJfszAU1QGTqU+fE+JHXQQ=="