image:
  repository: "216612008115.dkr.ecr.us-east-1.amazonaws.com/lesson7-django-repo"
  tag: latest

service:
  type: LoadBalancer
  port: 80

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

env:
  DJANGO_SECRET_KEY: "secret"
  DJANGO_DEBUG: "True"
  ALLOWED_HOSTS: "*"

postgresql:
  enabled: false
  host: "prod-db.cwxgmq8gqhxc.us-east-1.rds.amazonaws.com"
  port: "5432"
  db: "postgres"
  user: "postgres"
  password: "postgres"