apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nc -z {{ .Values.postgresql.host }} {{ .Values.postgresql.port }} -w 2; do echo "Waiting for PostgreSQL..."; sleep 5; done; echo "PostgreSQL ready!";' ]
        - name: run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['sh', '-c', 'python manage.py migrate']
          envFrom:
            - configMapRef:
                name: django-config
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5