apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: django-app
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-internal
spec:
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP